lib/connect.js, test/connect.js
Since `connect()` does not return the socket instance, there is currently no easy way to set the connection timeout. This PR adds a `timeout` option to the socket options passed to `connect()`, and automatically sets it on the socket when connecting. If a timeout is reached, it will trigger the connect callback with an error.
This should solve #88 .
=> Allow specifying connection timeout in socket options

lib/connect.js, lib/connection.js, test/connect.js
When implementing keep-alive support I just pulled in the work from @rexxar on timeouts as i slightly refactored it to handle timeout events that could possibly happen after connect (which I have not seen but was going for the side of safety). @squaremo let me know your thoughts as I think having keep-alive support is a nice complement to the heartbeat functionality you have implemented.
=> Add keep-alive and timeout options (thanks @rexxar)

.travis.yml, package.json
@squaremo - Here at Lanetix we are using amqplib with iojs v1 - v1.6.2 and it works well.
Since all iojs-v1.x.x should be backward compatible, there is no reason to specify a specific iojs version in the package.json file.
This change will remove the warning we see when we install amqplib using npm with the latest versions of iojs (ex: 1.6.2).
Thanks,
-Oron
=> node: ">=0.8 <0.13 || ^1"

lib/channel.js, test/channel.js
=> Add error code into channel error object.

lib/connect.js
The built in url.parse() does not properly handle encoded variables in the username or password. Consequently, some username and/or passwords can not be based to amqplib as a URL. For reference, see: https://github.com/joyent/node/issues/25353
So, I updated connect() to support passing connection parameters as an object:
```javascript
var url = {
protocol: 'amqp', //amqp or amqps
username: 'someone',
password: 'secret',
hostname: '127.0.0.1',
port: 5672,
vhost: 'name'
}
connect([url, [socketOptions]], function(err, conn) {...})
```
=> add support for passing connection parameters as an object

lib/api_args.js
I'm working on project that benefits from using priority queues in RabbitMQ (available since version 3.5.x). I feel that others might benefit from this functionality too.
=> Support priority queue declarations

.travis.yml
Travis uses nvm to install node. By adding the "node" option to `node_js` configuration you enforce your test to run on latest node version. 
I updated the `before_install` hook to ensure that npm v2 is installed unless current travis VM is running node V5 because node V5 comes with npm v3.
=> test latest node. See nvm "node" alias

README.md
Added documentation on how to use docker to run the testsuite
=> Run tests with docker

README.md
The original Promise API example in README has a few exhibition of what's now considered to be [Promise bad practices](https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html), namely:
1. Not utilizing the otherwise elegant feature of "chained-then" pattern.
2. (Also related 1.) Not utilizing `catch` and instead utilizing somewhat inferior `rejectHandler` interface.
In the future, it'll be a great user-experience boost if the `callback_api` can be "merged" with the promise API so that if no callback is given, it automatically returns a promise, like many other libraries do.
=> Better Promise Example in README

lib/heartbeat.js
I know this is not pressing but when I was going through this project
trying to learn more about the heartbeat part of RabbitMQ I noticed
that this link was no longer valid as that part has been moved out into
the rabbitmq-commom package.
Todd Pickell @tapickell <tapickell@gmail.com>
=> Updates the url that links to rabbit_heartbeat.erl

channel_api.js, examples/tutorials/README.md, examples/tutorials/emit_log.js, examples/tutorials/emit_log_direct.js, examples/tutorials/emit_log_topic.js, examples/tutorials/new_task.js, examples/tutorials/package.json, examples/tutorials/receive.js, examples/tutorials/receive_logs.js, examples/tutorials/receive_logs_direct.js, examples/tutorials/receive_logs_topic.js, examples/tutorials/rpc_client.js, examples/tutorials/rpc_server.js, examples/tutorials/send.js, examples/tutorials/worker.js, examples/waitForConfirms.js, lib/callback_model.js, lib/channel_model.js, package.json, test/channel.js, test/channel_api.js, test/util.js
This is a new take on #158. I realize, since that PR has been seating there for a year and a half now, it won't ever be updated.
I won't add much to what was already commented on #158, except that this time around everything seems to be working fine, including unit tests. No API changes, AFAIK. This should be completely transparent to users. It also gets rid of the so-called ["deferred anti-pattern"](http://bluebirdjs.com/docs/anti-patterns.html), widely used in the library.
=> Migrate when -> bluebird

lib/channel_model.js, test/channel_api.js
Fixes #297. Also adds a unit test to cover `Channel#close()`.
=> Fix bad this reference on Channel#closeBecause

examples/receive_generator.js
I was looking for an example for a receive generator and saw an example for the a send generator. Here is a one for the reception of messages. It simply sends a message and consumes it within a generator using the 'co' library.
=> add a consume example using a generator in a co routine

lib/connect.js, test/connect.js, test/util.js
Provide extra settings inside the object configuration that were only available from url configs
like heartbeat interval.
Closes #229
=> Specify heartbeat with object configuration

callback_api.js, channel_api.js
#299 
```javascript
const amqp = require('amqplib');
const IllegalOperationError = amqp.IllegalOperationError;
```
or
```javascript
const amqp = require('amqplib/callback_api');
const IllegalOperationError = amqp.IllegalOperationError;
```
=> exposes IllegalOperationError to public API

lib/connect.js
Split the username and password correctly so that the password can contain a ':' character.
=> Split the username and password correctly

lib/connect.js
Close socket on timeout to prevent dangling connections.
=> Fix dangling connection on timed out socket.

channel_api.md
Was wondering why I couldn't disable heartbeat by configure value of `0`.
https://github.com/squaremo/amqp.node/blob/f485a2c84122d72b3eff6d0e52478f97de2bfcc9/lib/connection.js#L186-L199
Edit: Turns out it's not just me who is confused https://github.com/squaremo/amqp.node/issues/344
=> Fix ambiguous heartbeat documentation

Makefile, lib/codec.js, test/codec.js, test/data.js
Implements the suggestion in #358.
=> Support giving explicit type with '!'

lib/connect.js, package.json, test/connect.js
The `url.parse` from the standard lib provides the username and
password as one field, and decodes them. This means any
percent-encoded characters are decoded, and it's impossible to tell
whether a colon is the delimiter between the username and password, or
was encoded and part of one or other.
Newer versions of the Node standard library come with an updated URL
parser. However, I would like to work with older versions of Node, so
I've used a third party parser.
Fixes #385 and possibly helps #392.
=> Use a third-party URL parser

channel_api.md
The document mentions that `ConfirmChannel#publish` and `ConfirmChannel#sendToQueue` does not return promises in the promise API under [flow control](http://www.squaremobius.net/amqp.node/channel_api.html#flowcontrol) but not under the section titled **ConfirmChannel**
=> Add method for ConfirmChanne#publish and ConfirmChanne#sendToQueue

lib/api_args.js
Now when you declare a queue you can specify the overflow option (eg. "reject-publish"). ([documentation](https://www.rabbitmq.com/maxlength.html#overflow-behaviour))
Usage:
`await ch.assertQueue(q, { overflow: 'reject-publish' });`
=> Add overflow option to be set.

bin/generate-defs.js, lib/channel.js, test/channel.js
This change adds a `methodId` and `classId` property to the channel errors.
I have a higher level configuration for the topology that allows automatic deletion of exchanges and queues. I perform a `deleteExchange`/`deleteQueue` with `ifUnused`/`ifEmpty` options set, and against exchanges and queues that no longer exist. These operations will fail with an error in some cases. Currently it is only  possible to determine if there was a `precondition­failed` error code (406) and not what operation failed. In the case of bad topology, for example a binding to a queue that does not exist, I produces a critical error fault in our monitoring system. In the case of a failure to delete an exchange or queue, I want to ignore the error, but currently cannot. With this change, errors will contain the …
=> Add method and class IDs to channel errors

package.json
The test suite fails on a couple of test cases which succeed
individually, just in older versions of Node. Running the tests with a
path ending in test/*.js (rather than test/) averts the test
failures. So does upgrading mocha.
I have bumped it to 3.5.3, which is the newest version that still
supports NodeJS <4.
While I was at it, I upgraded a few other packages.
=> Bump mocha to fix stray failures

lib/channel.js, package.json
This gets rid of some `Buffer` misuse deprecation notices.
=> Bump bitsyntax to 0.1.0

.npmignore, lib/channel.js, package.json, test/channel_api.js
Otherwise waitForConfirms never terminates or terminates node
Additional this includes a commit https://github.com/squaremo/amqp.node/commit/099673edefdc3a7b570027c6f48793bbecf5789b, which makes it possible to install this module directly from git (instead of the published package), but I'm happy to drop this if preferred.
=> Error pending confirmation callbacks on channel close

.travis.yml
RabbitMQ doesn't appear to be supported natively by TravisCI any
more. It disappeared in the upgrade from Trusty to Xenial.
To use it, yuo have to install it yourself, which I do here using an
addons.apt stanza.
=> Install RabbitMQ as prereq of CI

package.json
Based on the current `.travis.yml`, node version 10, 11, 12 are supported. I have updated the package.json to reflect that. Otherwise amqplib fails to install when users have flag `engine-strict=true` in their .npmrc.
=> Update package.json to reflect supported node versions

lib/mux.js, test/mux.js
I'm not really sure how to test this for real, but under constant publishing I can trigger an occasional `Uncaught AssertionError [ERR_ASSERTION]: 0 == 1` https://github.com/squaremo/amqp.node/blob/c28c176dd74565c73957eebf00932a892d2aa840/lib/mux.js#L92
It seems that some kind of stream in this library is emitting `readable`, during read calls and causing this assertion to trip.
=> Fix stream becoming readable again

examples/tutorials/package.json
The node-uuid module is deprecated and should not be used any more. Change this dependency to uuid module is appropriate.
=> Update the deprecated module with new module

.travis.yml, package.json
Fixes https://github.com/squaremo/amqp.node/issues/549.
We are using `amqp.node` with the latest NodeJS version (i.e. 13 and 14) but unfortunately,
`amqp.node` has its `package.json` fixed to an older version of NodeJS (12).
This PR has two commits:
- One for allowing newer engines of NodeJS
- The other to support those new engines in travis
=> Allow newer node version

Makefile, README.md, package.json
It's a common practice to drop support for non-LTS Node versions, as it allows to reduce the maintenance burden. See more at:
https://nodejs.org/en/about/releases/
* [aws](https://aws.amazon.com/blogs/compute/node-js-14-x-runtime-now-available-in-aws-lambda/) supports nodejs v14, v12, v10 (will not be available soon)
* [gcd](https://cloud.google.com/appengine/docs/standard/nodejs/runtime#node.js-14) supports nodejs v14, v12, v10, v8 (deprecated)
Also, I see artifacts in the code
> something broken about domains in Node.JS v0.8 and mocha
or
```js
function isFloatingPoint(n) {
return n >= 0x8000000000000000 ||
(Math.abs(n) < 0x4000000000000
&& Math.floor(n) !== n);
```
instead of `Number.isSafeInteger(n)` (appeared in v0.12).
My future PRs will be based on this.
=> Drop support for node.js engines below v10

lib/connect.js
Is required if you have multiple AMQP servers behind a TLS load balancer.
=> set SNI hostname for TLS connections

.travis.yml
Support for Node prior to v10 has been removed. It would be nice to check against older NodeJS versions, but it can't be required by CI.
=> Remove old NodeJS versions from CI matrix

lib/connect.js, test/connect.js
A minimal pull request to fix open socket leak after e.g. authentication error on connect. This is a part of the fix in #584, but I have only kept the most essential part and added a test.
By keeping this as small as possible, I hope to remove any hesitance so that it can be merged.
=> Close connection to server on connect errors

lib/connection.js
Fixes CI with node version 10.
The problem was that the steps in `afterStartOk` weren't aborted even though an error was detected and `bail` was called. Thus the callback was called at least twice.
=> fix: done called twice on invalid options

CHANGELOG.md, package-lock.json, package.json
* Update mocha and replace the deprecated istanbul with nyc ([PR 681](https://github.com/squaremo/amqp.node/pull/681)
* Update url-parse ([PR 675](https://github.com/squaremo/amqp.node/pull/675), thank you @suhail-n and @kibertoad)
* fix: done called twice on invalid options ([PR 667](https://github.com/squaremo/amqp.node/pull/667), thank you @luddd3 and @kibertoad)
* Close connection to server on connect errors ([PR 647](https://github.com/squaremo/amqp.node/pull/647), thank you @luddd3 and @kibertoad)
* Modernise channel_model.js ([PR 635](https://github.com/squaremo/amqp.node/pull/635), thank you @kibertoad and @jimmywarting)
* Bring package-lock.json up to date ([PR 653](https://github.com/squaremo/amqp.node/pull/653)
* Update url-parse ([PR …
=> Preparing for 0.9.0

channel_api.md
I've tried to resolve https://github.com/amqp-node/amqplib/issues/294 by being more explicit about when operations do not return a promise / expect a callback.
=> Reduce readme ambiguity for operations that do not have a reply

lib/mux.js
Also
remove unused require
remove unused self variable
#657
Should reduce memory footprint and performance
=> use .push.apply instead of concat in Mux _readIncoming

lib/channel.js
@squaremo 
While analyzing amqplib in sonarqube I found that some throws do tot throw an Error-Object but merely a string. 
If you now run the tests, two of them fail. 
```
1) Consume from non-queue invokes error k
2) bad delivery
```
Responsible for failing these tests is the change in line 346. 
I suspect, that this is a valid code smell but I quite dont understand how I could fix this.
=> transform throws string into throw Error

lib/channel.js
This PR uses a Map instead of an Object for BaseChannel.consumers. It should improve the performance while running in node, as the amount of V8-HiddenClasses will be reduced. 
Use Case: If in your implementation alot of consumers get created and canceled, alot of unique V8-HiddenClasses will be created in V8 at runtime. 
Information regarding HiddenClasses:
https://v8.dev/blog/slack-tracking
=> Use Map instead of Object for BaseChannel.consumers

lib/channel.js
This PR adds a call to unregisterConsumer in handleCancel. This ensures, that the consumer gets removed from this.consumers.
Fixes #585
=> call unregisterConsumer in handleCancel

lib/connection.js
`Buffer.allocUnsafe` will prefer to create non-zeroed buffers using the buffer pool rather than creating a new zeroed buffer each time like `Buffer.alloc`. Despite the name, `Buffer.allocUnsafe` is safe to use if you are immediately overwriting all the content in the buffer, and it is preferred for library APIs that will be called a lot or will be doing a lot of allocations.
https://nodejs.org/api/buffer.html#static-method-bufferallocunsafesize
=> Use Buffer.allocUnsafe to reduce allocations and CPU usage

bin/generate-defs.js, lib/codec.js, lib/connection.js, lib/credentials.js, test/codec.js, test/frame.js
it was bad of NodeJS to override slice with an alias of subarray that dose two different things... if ppl actually wish to make a new sub-view of same underlying buffer then they should have actually used subarray instead which cased confusion from developer thinking that `slice()` would cause a immutable copy.
so they have now [deprecated buffer.slice](https://nodejs.org/dist/latest-v20.x/docs/api/buffer.html#bufslicestart-end)
=> chore: slice -> subarray

Makefile, lib/callback_model.js, lib/channel_model.js, lib/connection.js, test/callback_api.js, test/channel_api.js
Add support connection update-secret as per https://github.com/amqp-node/amqplib/issues/755. I have asked @mortdiggiddy to test
=> Add connection-update-secret

lib/codec.js, test/codec.js, test/data.js
This PR completes the work started by @ebrinette in https://github.com/amqp-node/amqplib/pull/766. The noteable changes are...
1. Add missing break statement
2. Change 'unsigned byte' to 'unsignedbyte'
3. Add tests
=> Support for unsigned int edits

lib/codec.js
Add support for unsigned int (uint8, uint16, uint32) as specified in https://www.rabbitmq.com/amqp-0-9-1-errata#section_3.
Ignore uint64 to avoid conflict mentionned in #646.
=> Support for unsigned int

channel_api.md
- Fix typos
- Fix idempotent-deletes anchor
- Update official RabbitMQ documentation links
=> Fix Channel API documentation

lib/connection.js, package-lock.json, package.json, test/frame.js, test/mux.js, test/util.js
Removes readable-stream since the native streams are available since 0.10.x
=> Remove readable-stream - see #729

lib/callback_model.js, lib/channel.js, lib/channel_model.js, test/callback_api.js
Allows setting channel options like highwatermark. See https://github.com/amqp-node/amqplib/issues/264
=> Support channel options like highwatermark

lib/connect.js
Just like nearly all client libraries do.
In RabbitMQ 4.1.0, the pre-authentication default changes to 8192 to accommodate for larger JWT frames, which the current value in this client won't be compatible with. See [1].
This default matches what RabbitMQ itself, the Java and .NET clients have been using since 2007.
1. https://github.com/rabbitmq/rabbitmq-server/blob/main/release-notes/4.1.0.md#initial-amqp-0-9-1-maximum-frame-size
=> Use a frame_max of 131072 by default for RabbitMQ 4.1.0 compatibility

lib/connection.js, lib/frame.js, test/frame.js
When you first saw this you must have thought I was crazy and wanted to close this pr immediately, but I would like to ask you to bear with me and listen to my reasons!
I understand that the AMQP 0-9-1 protocol requires that the server and client must respect frame max
> frame-max: the largest frame size that the server proposes for the connection. The client can negotiate a lower value. Zero means that the server does not impose any specific limit but may reject very large frames for internal reasons.
> Once negotiated, both parties MUST NOT send frames exceeding this size.
>	When a message is too large to fit within a single frame, it must be split into multiple frames.
However, in reality, some cloud server vendors do not necessarily comply with this specification for cost reasons, …
=> dont check frame max size when parse

README.md
Mentions the minimum required version for RabbitMQ 4.1.0 compatibility.
=> README: a note on RabbitMQ 4.1.0 compatibility

lib/connect.js, test/connect.js
See https://github.com/amqp-node/amqplib/issues/794
=> Add support for ipv6 urls
